# Generated by Django 5.0.7 on 2024-08-10 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SwipeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swipe',
            name='swiped_is_like',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='swipe',
            name='swiper_is_like',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
