# Generated by Django 5.0.7 on 2024-08-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SwipeApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationsUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(unique=True)),
                ('quantity_activation', models.IntegerField(default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='swipe',
            name='swiped_is_like',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='swipe',
            name='swiper_is_like',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
