# Generated by Django 5.0.7 on 2024-07-23 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SwipeApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='surname',
        ),
        migrations.AddField(
            model_name='user',
            name='sur_name',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
