# Generated by Django 5.0.7 on 2024-07-25 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SwipeApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='swipe',
            name='is_swiped_like',
            field=models.BooleanField(default=False),
        ),
    ]
