# Generated by Django 5.0.7 on 2024-08-19 11:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SwipeApp', '0002_invitationsuser_alter_swipe_swiped_is_like_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationsuser',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
