# Generated by Django 5.0.7 on 2024-07-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SwipeApp', '0002_remove_user_surname_user_sur_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_boy',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='imagesUser/'),
        ),
    ]
