# Generated by Django 5.0.7 on 2024-11-26 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SwipeApp', '0003_alter_invitationsuser_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_search_friend',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_search_love',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
