# Generated by Django 5.0.7 on 2025-06-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SwipeApp', '0005_user_block_reason_user_is_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintlist',
            name='created_at',
            field=models.DateTimeField(default=None),
        ),
    ]
