# Generated by Django 5.0.7 on 2025-06-02 17:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SwipeApp', '0006_complaintlist_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintlist',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
